language: julia
notifications:
  email: false
julia:
  - 1.0
  - 1.2
  - nightly
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
  include:
    - stage: Documentation
      julia: 1.0
      script: julia --project=docs -e '
        using Pkg;
        Pkg.develop(PackageSpec(; path=pwd()));
        Pkg.instantiate();
        include(joinpath("docs", "make.jl"));'
      after_success: skip
